### ISSUE TITLE
Failed to Load Function: Intermittent Function Failures

### ISSUE THREAD

**Issue by jelling** [firebase/firebase-functions-python#104]
I have a long-running (~75s) Python cloud function that works with the emulator and also works when deployed. But intermittingly, it fails in the emulator with the error:

```
Failed to handle request for function us-central1-script_infer_api 
FirebaseError: Failed to load function
```

The function signature is:
```
@https_fn.on_request(timeout_sec=300, memory=options.MemoryOption.GB_2)
def script_infer_api(req: https_fn.Request) -> https_fn.Response:
```

I ran the emulator in verbose mode but it didn't tell me anything more, either. Is there another way to increase the logging?

Firebase cli: version 12.3.1 (latest)

**Comment by russellwheatley** [comment]
Hey @jelling, could you provide a code sample so we can reproduce and take a look at this issue?

**Comment by jelling** [comment]
Closing this since I just worked around it but forgot how
