### ISSUE TITLE
Allow import of relative files in main.py

### ISSUE THREAD

**Issue by Afirium** [firebase/firebase-functions-python#124]
Local module import still doesn't work.
I am using the recommended python version 3.11 and the latest firebase-functions-python==0.1.1

[fix: add cwd to sys.path for functions yaml] https://github.com/firebase/firebase-functions-python/pull/12

**Comment by russellwheatley** [comment]
Hey @Afirium, could you provide a repro repository for me to clone, please? I'm wondering if this is because of how you've setup your project. Thanks.
