### ISSUE TITLE
Issue when deploying

### ISSUE THREAD

**Issue by nikhilkotiya** [firebase/firebase-functions-python#128]
Hello everyone,

I am writing this email to address some challenges we've encountered while attempting to deploy Firebase functions. Currently, when we deploy a single function using the command "firebase deploy --only functions:function_name," the deployment process works smoothly and the function is correctly deployed. However, when we utilize the command "firebase deploy --only functions" to deploy all functions, we're encountering an issue where all the functions end up with the same container image URL. As a result, this is causing requests to be directed to only one function instead of the intended target functions.

Thank you.

**Comment by exaby73** [comment]
Hello @nikhilkotiya. Could you provide a reproducible code sample that I may test with? Could you also provide the output of `pip freeze` and your python version?

**Comment by nikhilkotiya** [comment]
reproducible code
@on_document_created(document="geo_data/{userId}", region="asia-northeast1", max_instances=10)
def geo_grid(event: Event[DocumentSnapshot]) -> None:
    print(' geo_grid')
    return "done"


@scheduler_fn.on_schedule(schedule="*/2 * * * *", region="asia-northeast1", max_instances=10)
def helper(event: scheduler_fn.ScheduledEvent) -> None:
    print(' helper')
    return "done"


So when i run firebase deploy --only functions the container image URL is create same for both the functions it mean both the cron trigger only 1 function(not specified function but same). And their log is same also.

pip freeze
```
beautifulsoup4==4.12.2
blinker==1.6.2
bs4==0.0.1
CacheControl==0.13.1
cachetools==5.3.1
certifi==2023.7.22
pandas==2.0.3
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
cloudevents==1.9.0
cryptography==41.0.2
deprecation==2.1.0
dnspython==2.4.1
firebase-admin==6.2.0
firebase-functions==0.1.1
Flask==2.3.2
Flask-Cors==4.0.0
functions-framework==3.4.0
google-api-core==2.11.1
google-api-python-client==2.95.0
google-auth==2.22.0
google-auth-httplib2==0.1.0
google-cloud-core==2.3.3
google-cloud-firestore==2.11.1
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-events==0.10.0
google-resumable-media==2.5.0
googleapis-common-protos==1.59.1
grpcio==1.56.2
grpcio-status==1.56.2
gunicorn==20.1.0
httplib2==0.22.0
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
msgpack==1.0.5
ndg-httpsclient==0.5.1
packaging==23.1
proto-plus==1.22.3
protobuf==4.23.4
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyJWT==2.8.0
pymongo==4.3.3
pyOpenSSL==23.2.0
pyparsing==3.1.0
python-dotenv==1.0.0
PyYAML==6.0.1
requests==2.31.0
rsa==4.9
six==1.16.0
soupsieve==2.4.1
typing_extensions==4.7.1
uritemplate==4.1.1
urllib3==1.26.16
watchdog==3.0.0
Werkzeug==2.3.6
redis==4.6.0
```


python version Python 3.11

**Comment by nikhilkotiya** [comment]
@exaby73  please look into this bug i have 30+ firebase functions. Its difficult for me to deploy single single function. @antont  Have the same issue.

**Comment by antont** [comment]
> **@exaby73** please look into this bug i have 30+ firebase functions. Its difficult for me to deploy single single function. @antont Have the same issue.

Yep. I can confirm that this happened when trying to deploy all functions normally, but deploying one-by-one works. I am doing that for the few that have now, but it would not be practical for many.

**Comment by exaby73** [comment]
Hello. Just a small update. I am working on this bug, trying to track it down and fix it. I think I'm close, so please bear with me :)

**Comment by nikhilkotiya** [comment]
cool!

**Comment by berengamble** [comment]
I had this issue. I upgraded to the latest firebase CLI and it fixed it. `npm install -g firebase-tools`

**Comment by antont** [comment]
> I had this issue. I upgraded to the latest firebase CLI and it fixed it. `npm install -g firebase-tools`

Yay that fixed it for me too! I had upgraded already earlier but hadn't retried this after that yet. Thanks for info!

**Comment by nikhilkotiya** [comment]
Yeah fixed. 
I have one more question, is there any way to use debugger with firebase functions

**Comment by exaby73** [comment]
Based on https://github.com/firebase/firebase-functions-python/issues/128#issuecomment-1713923659, I will close this issue as fixed.
