### ISSUE TITLE
Crash, when is trying to sign up with Apple or Google providers

### ISSUE THREAD

**Issue by yura-hb** [firebase/firebase-functions-python#133]
Hi,

I'm experiencing a crash when a new user is created via the Apple or Google provider for the `@identity_fn.before_user_created()` trigger. The stack trace is as follows:

<img width="2136" alt="Screenshot 2023-09-10 at 13 35 11" src="https://github.com/firebase/firebase-functions-python/assets/23167917/4158b7f8-97a0-44c1-9f6e-352cfbdc8c3b">

User authentication is done using firebase-ios-sdk and the source code is the following

```
try await auth.signIn(with: credential.credential)
```

I'm using Python 3.11 and firebase functions version 0.11.0. Could you please check the problem?

Best regards,
Yury Hayeu

**Comment by yura-hb** [comment]
Hi, yes it is missing

<img width="2182" alt="Screenshot 2023-09-11 at 19 50 53" src="https://github.com/firebase/firebase-functions-python/assets/23167917/c08f5e5f-1077-46ce-b5a2-3f7260a6da72">

**Comment by exaby73** [comment]
Could you provide sample code of the function you're running?

**Comment by yura-hb** [comment]
Hi, it wouldn't even get to the function call, so this should suffice

```
@identity_fn.before_user_created(id_token=True)
def prepare_user_data(event: identity_fn.AuthBlockingEvent) -> identity_fn.BeforeCreateResponse | None:
   user = event.data
   uid = user.uid
   
   return identity_fn.BeforeCreateResponse()
```
