### ISSUE TITLE
Types are not exported

### ISSUE THREAD

**Issue by gijswobben** [firebase/firebase-functions-python#163]
`mypy` is complaining that the decorators don't have types:

![image](https://github.com/firebase/firebase-functions-python/assets/3183856/dcc38d7e-1afd-4f81-9f60-156be13dab77)

The package does have types, also on the decorators, but they are not exported because there is not `py.typed` file. The easy fix is to add this file and release a new version of the package.

More information about `py.typed`:
https://peps.python.org/pep-0561/
https://mypy.readthedocs.io/en/stable/installed_packages.html

**Comment by exaby73** [comment]
Hello @gijswobben. Are you getting this error on all decorators, or only some of them? Could you let me know which version of `mypy` you're using?

**Comment by exaby73** [comment]
Do you get the same for a simple example like:

```python
from firebase_functions import pubsub_fn


@pubsub_fn.on_message_published()
def some_function():
    pass
```

After running `pylint main.py`, I get unrelated lints:

```console
************* Module main
main.py:1:0: C0114: Missing module docstring (missing-module-docstring)
main.py:5:0: C0116: Missing function or method docstring (missing-function-docstring)

------------------------------------------------------------------
Your code has been rated at 3.33/10 (previous run: 0.00/10, +3.33)
```

**Comment by exaby73** [comment]
Okay so the functions that are decorated are not typed which is the problem, but all the other APIs are typed. This seems like a valid issue and I'll label it. Thanks for catching this one :)

**Comment by gijswobben** [comment]
> Okay so the functions that are decorated are not typed which is the problem, but all the other APIs are typed. This seems like a valid issue and I'll label it. Thanks for catching this one :)

No, you can actually see the types on the decorator function `on_message_published`. They are there, but types are not exported by default in Python. You have to explicitly export them if you make a library, either through stubs, or by creating a `py.typed` file.

You can read all about this error on the great documentation by `MyPy`: https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker

From the documentation:

> Mypy will not try inferring the types of any 3rd party libraries you have installed unless they either have declared themselves to be [PEP 561 compliant stub package](https://mypy.readthedocs.io/en/stable/installed_packages.html#installed-packages) (e.g. with a py.typed file) or have registered themselves on [typeshed](https://github.com/python/typeshed), the repository of types for the standard library and some 3rd party libraries. 

The fix is rather easy, just add a `py.typed` file.

**Comment by exaby73** [comment]
You're welcome to make a PR :) If you do, you can read about [our contributing guidelines](https://github.com/firebase/firebase-functions-python/blob/7f83050dc44f7877a58a590a5aae1006a6f14358/.github/CONTRIBUTING.md)

**Comment by gijswobben** [comment]
@exaby73, sure, please have a look at:
https://github.com/firebase/firebase-functions-python/pull/169
