### ISSUE TITLE
CORS Error on_call Cloud Function

### ISSUE THREAD

**Issue by georgiossalon** [firebase/firebase-functions-python#170]
The CORS configuration provided by the official documentation is inadequate. Meaning:

According to this documentation [Configuring CORS (Cross-Origin Resource Sharing)](https://firebase.google.com/docs/functions/http-events?gen=2nd#configuring_cors_cross-origin_resource_sharing) I tried to implement the CORS for my Firebase CF in Python like the following:

```
@https_fn.on_call(region='europe-west3', cors=options.CorsOptions(
        cors_origins="*",
        cors_methods=["get", "post"],))
def some_function():
 ...
```
Then I deployed succesfully the CF to firebase with `firebase deploy --only functions:some_function`

Even though I entered * for testing purposes since I was also failing with r"https://my-domain-1a0a0.web.app" in the cors_origins I still get

> Access to fetch at 'https://europe-west3-my-domain.cloudfunctions.net/some_function' from origin 'https://my-domain.web.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I dont know if this helps, but I did inspect the Headers and found the following: `Access-Control-Request-Headers: authorization,content-type `

In case it is important, I am using Flutter Web and I am triggering the Python CF via the UI.

**Comment by exaby73** [comment]
Hello @georgiossalon. When you say you're triggering the functions from the UI, you mean the link present in the Firebase Dashboard?

**Comment by exaby73** [comment]
In any case, I am able to reproduce the issue with both Python and Node functions.

Here is the Python example I tested:

```python
@https_fn.on_call(region=options.SupportedRegion.ASIA_SOUTH1, cors=options.CorsOptions(
    cors_origins="*", cors_methods=["get", "post"]))
def hello_world_call(_: https_fn.CallableRequest) -> dict[str, Any]:
    return {
        "status": "success",
        "message": "Hello from Firebase Functions!"
    }
```

And the Node one:

```ts
export const helloWorldCall = onCall(
  {
    cors: "*",
  },
  (_) => {
    return {
      message: `Hello from Firebase!`,
    };
  }
);
```

I called the function using the JS SDK with the following code:

```ts
const functions = getFunctions();
// Node call
const hello = httpsCallable(functions, 'helloWorldCall');
// Python call
const hello = httpsCallable(functions, 'hello_world_call');
```

**Comment by ma-anwar** [comment]
Bumping this to add that in the Web SDK there is no way to configure the `access-control-allow-headers`.

I have resorted to using a custom decorator I found on [Stackoverflow](https://stackoverflow.com/questions/77140606/use-of-cors-in-firebase-functions-in-python-to-set-allow-headers).

Furthermore, none of this works if I'm raising an `HttpsError` as the headers aren't attached in that case and I always end up with a CORS error. 

I am not able to repro this issue in js (js sdk I have been using for months just fine)

**Comment by pgainullin** [comment]
> Bumping this to add that in the Web SDK there is no way to configure the `access-control-allow-headers`.
> 
> I have resorted to using a custom decorator I found on [Stackoverflow](https://stackoverflow.com/questions/77140606/use-of-cors-in-firebase-functions-in-python-to-set-allow-headers).
> 
> Furthermore, none of this works if I'm raising an `HttpsError` as the headers aren't attached in that case and I always end up with a CORS error.
> 
> I am not able to repro this issue in js (js sdk I have been using for months just fine)

Having the same issue after updating my functions that were working perfectly fine previously. Tried to implement the solution here https://stackoverflow.com/questions/77635964/cors-preflight-check-error-google-cloud-firebase-python-function-reactjs but so far no luck. My NodeJS functions with the same settings continue working fine...

**Comment by georgiossalon** [comment]
> Hello @georgiossalon. When you say you're triggering the functions from the UI, you mean the link present in the Firebase Dashboard?

The triggering part happens in a Flutter Web App via the tap of a button:

`final firebaseFunctions = FirebaseFunctions.instanceFor(region: 'europe-west3');`
        
  and within an onTap
  
```
final optiCF = firebaseFunctions.httpsCallable('some_function');
final result = await optiCF();
```

**Comment by exaby73** [comment]
I was unable to reproduce this issue but I see it's still an issue. @georgiossalon were you able to reproduce it with the samples I tried in https://github.com/firebase/firebase-functions-python/issues/170#issuecomment-1938149204?

**Comment by exaby73** [comment]
That's interesting. Could you give me the commands you were using previously, and the one you are now if they are different to `gcloud functions deploy --gen2`? Also, just so that I can understand your use case, why not use `firebase deploy --only functions` which would have automatically detected gen2 functions?

**Comment by georgiossalon** [comment]
@exaby73 

That is the full command. Now I only added the --gen2 flag. Before doing so, I deleted it first and then re-deployed it with the command.

`gcloud functions deploy function_name --trigger-http --runtime python310 --region europe-west3 --entry-point executed_function --project project_id --source functions --gen2`

I was not aware that `--gen2` can be omitted. I can't explain why this solved it. At the same time, I am not the only person that had this problem, so maybe there is something in there to be explored.

**Comment by exaby73** [comment]
Sorry to repeat the question, but it there a reason why you've not used the Firebase CLI instead? Is there something missing in `firebase deploy` that you need for your project?

**Comment by georgiossalon** [comment]
@exaby73 I did use the firebase CLI from the beginning. As mentioned updating the deployment of the CF solved my issue. Why exactly I can not tell. I'll close the issue. Maybe the rest of the people who still have issues with it should open a new one.
