### ISSUE TITLE
KeyError: 'datacontenttype'

### ISSUE THREAD

**Issue by edump72** [firebase/firebase-functions-python#187]
I am creating a Google Cloud Function using a Python script, in order to handle the creation of a new document in my Firestore database. When the data of the new document is fetched, I create an SVG with it using Spacy. I have used the documentation in order to handle this event : https://firebase.google.com/docs/functions/firestore-events?hl=es-419&gen=2nd#python-preview_1

This is my Python script : 

```python
from firebase_functions import firestore_fn, https_fn
from firebase_admin import initialize_app, firestore
from spacy import displacy
import google.cloud.firestore
#Spacy
import spacy


app = initialize_app()

 @firestore_fn.on_document_created(document="Solicitud desde Android Studio/Entidades")
 def sentenceToImageFunction(event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None]) -> None:

   firestore_client: google.cloud.firestore.Client = firestore.client()
   nlp = spacy.load("es_dep_news_trf")
   # Get the value of "Oración" if it exists.
   if event.data is None:
       return
   try:
       sentence = event.data.get("Oración")
   except KeyError:
       # No "Oración" field, so do nothing.
       return

   nlp = spacy.load("es_dep_news_trf")
   doc = nlp(sentence)
   options = {"compact": True, "bg": "#FFFFFF","color": "black", "font": "Arial", 
   "collapse_punct": True, "arrow_stroke": 5, "arrow_spacing": 10, "distance": 200}
   svg = str(displacy.render(doc, style="ent", options=options))

   firestore_client.collection("Respuesta desde Python").document("Entidades analizadas").set({"Entidad analizada" : svg})`
```

I have deployed the function using Google Cloud Console, setting everything correctly. The function is accepted, but when I enter a trigger event:
![CKm83](https://github.com/firebase/firebase-functions-python/assets/100035955/1d92bbb0-366a-4728-bb35-51c6424c885e)
,my Firestore database continues as it was and I get this error : 

```console
   [7:04:17 PM] - [2024-03-31 17:04:17,815] ERROR in app: Exception on / [POST]
   Traceback (most recent call last):
   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 1463, 
   in wsgi_app
   response = self.full_dispatch_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 872, in 
   full_dispatch_request
   rv = self.handle_user_exception(e)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 870, in 
   full_dispatch_request
   rv = self.dispatch_request()
     ^^^^^^^^^^^^^^^^^^^^^^^
   File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/app.py", line 855, in 
   dispatch_request
   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no- 
   any-return]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/layers/google.python.pip/pip/lib/python3.11/site- 
   packages/functions_framework/__init__.py", line 178, in view_func
   function(event)
   File "/layers/google.python.pip/pip/lib/python3.11/site- 
   packages/firebase_functions/firestore_fn.py", line 303, in on_document_created_wrapped
   return _firestore_endpoint_handler(
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/layers/google.python.pip/pip/lib/python3.11/site- 
   packages/firebase_functions/firestore_fn.py", line 95, in _firestore_endpoint_handler
   content_type: str = event_attributes["datacontenttype"]
                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
   KeyError: 'datacontenttype'
```

Anyone knows what is the problem? Thank you in advance!

**Comment by gregfenton** [comment]
Which version of the library are you using?

**Comment by exaby73** [comment]
Hey @edump72. Trying something similar, I cannot reproduce this issue. I get an error with the field name you're using:

```console
ValueError: Path Oración not consumed, residue: ón
```

Here's the code example I used:

```python
from firebase_functions import firestore_fn


@firestore_fn.on_document_created(document='Solicitud desde Android Studio/Entidades')
def on_post_created(event: firestore_fn.Event[firestore_fn.DocumentSnapshot]):
    print(event.data)
    if event.data is None:
        return

    try:
        event.data.get("Oración")
    except KeyError:
        return
```

**Comment by gregfenton** [comment]
Oh....is this an issue of Python and "non-ASCII" characters in field names?  Firestore is documented as supporting valid UTF-8 characters in field names, but maybe there's an issue with how Python is dealing with those strings?

[I haven't done a lot of Python coding in a long time, but I did suffer somewhat through the non-UTF8 wars of Python 2 vs. 3 ...]

**Comment by exaby73** [comment]
I believe that is a separate issue and not one with this SDK but rather upstream with the Google Cloud SDK we use internally. But what I don't get is how this error with `datacontenttype` occurred. My current speculation is that OP is using an older version of Google Cloud SDK which didn't have this issue but got another one by other means. This would mean that Google Cloud SDK has a regression. I'll raise this Unicode issue with the Firebase team, and keep this issue open for OP to respond if they can provide us with a reproducible sample

**Comment by CorieW** [comment]
I managed to reproduce this problem (but not with the error of `datacontenttype`) and I believe it's an issue with `python-firestore`, so I've created an issue there.

**Comment by CorieW** [comment]
Just relaying what was stated in [(python-firestore #1000)](https://github.com/googleapis/python-firestore/issues/1000):

It looks like the `field_path` module [was written to only support alphanumeric ascii characters](https://github.com/googleapis/python-firestore/blob/a1596a3ea66f4f7c08058134913130266c37c468/google/cloud/firestore_v1/field_path.py#L36). We should re-write it to support unicode, but we'll have to be careful not to break existing parsing functionality.

This is being marked as P3 in `python-firestore`, as there is a workaround. You should be able to use `event.data.to_dict[Oración]` to access and traverse the dict manually.
