### ISSUE TITLE
No stack trace in the log when an exception occurs

### ISSUE THREAD

**Issue by takahashi-shotaro-al** [firebase/firebase-functions-python#213]
(at least in emulated callable functions),  No stack trace in the log when an exception occurs, making it difficult to identify the cause.

```
>  ERROR:root:Unhandled error: list index out of range
i  functions: Finished "test" in 1998.7598480000001ms
```

Perhaps the stack trace is not output this line.
https://github.com/firebase/firebase-functions-python/blob/8610670b7cf9ecf79666fae50651509a71176a84/src/firebase_functions/https_fn.py#L410

**Comment by exaby73** [comment]
Hello. Stack traces are currently not supported in Python Cloud Functions hence no stack currently

**Comment by CorieW** [comment]
Closing as similar to [#172](https://github.com/firebase/firebase-functions-python/issues/172)
