### ISSUE TITLE
Don't convert function name with '_' to '-' - instead let CLI catch functions with invalid names

### ISSUE THREAD

**Issue by taeold** [firebase/firebase-functions-python#28]
https://github.com/firebase/firebase-functions-python/pull/25

**Comment by JackYBT** [comment]
Hello! After updating to the latest versions of the firebase function and firebase tools, I am still running into the issue where my "main.py" file does not found the module "flask_restful" when i try uploading it to cloud via "firebase deploy --only functions". I have already included "flask_restful" and its version in the "requirements.txt" file under the "functions" folder, however, it still does not recognize it. Any advice?
