### ISSUE TITLE
Early Access doc incorrect about Cors

### ISSUE THREAD

**Issue by RafaelZasas** [firebase/firebase-functions-python#58]
The docs state that the `cors` attribute may be `True to allow all origins or a str for an allowed origin` but this is not the case in usage.
The type for cors is `CorsOptions` which I could not find anywhere within the firebase functions or admin library.

Is CorsOptions a flask implementation? How can I allow my web app to communicate with the endpoint? Can I set cors globally?

**Comment by russellwheatley** [comment]
Hey @RafaelZasas, could you provide a link to the incorrect documentation, please?

**Comment by RafaelZasas** [comment]
It was the early access docs:
https://docs.google.com/document/d/1ZKD2Qz4xObij_z4MxOq_O3Kzhnj6n2pWbWPIarmqXyw/edit?usp=sharing&resourcekey=0-ar-SBFfZnxuJ8olzw8dDPw

I haven't taken a look at the official docs since the public release

**Comment by RafaelZasas** [comment]
I see that it is correct in the official documentation:
https://firebase.google.com/docs/functions/http-events?gen=2nd#configuring_cors_cross-origin_resource_sharing

**Comment by russellwheatley** [comment]
Great - looks like we can close this issue. Thanks for letting us know 👍
