### ISSUE TITLE
__str__ on Params incorrect

### ISSUE THREAD

**Issue by taeold** [firebase/firebase-functions-python#75]
Moved back to back log - change breaks a few things so internals needs a bit of a refactor. This bug is also present on JS Functions implementation

**Comment by taeold** [comment]
I can use params if I manually type "{{ params.COLLECTION }}" into my reference path, but not if I use f"{collection_param}". Maybe the __str__ method is broken?

**Comment by kevinthecheung** [comment]
#76 related?
