### ISSUE TITLE
Add a `logger` module to integrate with Cloud Logging

### ISSUE THREAD

**Issue by jhuleatt** [firebase/firebase-functions-python#79]
Create a Python equivalent of the Node [`logger` subpackage](https://firebase.google.com/docs/functions/writing-and-viewing-logs) to integrate with Cloud Logging's structured logs

Also include trace; https://github.com/firebase/firebase-functions/blob/aae1abd55930550636e8e95c41feefcb617edc9d/src/common/trace.ts#L6

**Comment by ekalosak** [comment]
Why not just format stdout logging as a valid UTF-8 JSON string? This is what I'm using and Cloud logging picks it up and parses it automatically. I wonder what value an additional module would be?
![Screen Shot 2023-09-11 at 11 08 40 AM](https://github.com/firebase/firebase-functions-python/assets/6068321/68148231-45ab-4399-9966-e3540e48fc2b)

**Comment by exaby73** [comment]
@ekalosak #121 does print JSON which is parsed by GCP

**Comment by scipilot** [comment]
>  I wonder what value an additional module would be?

Log levels would be one, debug/info/warning etc which can be filtered in the log viewer UI or help you setup an error alerting pipeline (e.g. Log Router to Big Query ingestion) without worrying about filtering out all the noisy logs.
https://firebase.google.com/docs/functions/writing-and-viewing-logs?gen=2nd#logger-sdk
