### ISSUE TITLE
Pip requirements.txt issue

### ISSUE THREAD

**Issue by JackYBT** [firebase/firebase-functions-python#97]
**Hello! After updating to the latest versions of the firebase function and firebase tools, I am still running into the issue where my "main.py" file does not found the module "flask_restful" when i try uploading it to cloud via "firebase deploy --only functions". I have already included "flask_restful" and its version in the "requirements.txt" file under the "functions" folder, however, it still does not recognize it. Any advice?**

**Comment by exaby73** [comment]
Hello @JackYBT. After adding to the `requirements.txt` file, did you run `pip install -r requirements.txt` in the `functions` folder?

**Comment by exaby73** [comment]
Since there hasn't been response in a while, I'll close this issue
